# Generated by Django 5.2.9 on 2025-12-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miningText', '0002_alter_article_options_article_date_modification'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='discours',
            field=models.FileField(blank=True, null=True, upload_to='discours/'),
        ),
    ]
