# Generated by Django 5.2.9 on 2025-12-26 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miningText', '0003_article_discours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_publication',
            field=models.DateTimeField(verbose_name=' auto_now_add=True '),
        ),
    ]
